language: python
python:
  - "2.7"

addons:
  apt:
    packages:
      - libnetcdf-dev
  
cache: pip

branches:
  only:
  - master
 
install:
  - pip install -U pip setuptools wheel
  - pip install -r requirements-build.txt
  - pip install -e .

script:
  - pytest -n3
